// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class CorrectnessofLink{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void CheckCorrectnessofLink() {
    System.setProperty("webdriver.chrome.driver","C:\\ChromeDriver\\chromedriver.exe");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:3000/feedback");
    driver.manage().window().maximize();
    String expectedURL="http://localhost:3000/";
    driver.findElement(By.id("homePageButton")).click();
    String redirectURL=driver.getCurrentUrl();
    Assert.assertEquals(redirectURL,expectedURL);
  }
}
