// Generated by Selenium IDE

import org.junit.After;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class FilterRooms {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void FilterRooms() {
    System.setProperty("webdriver.chrome.driver","C:\\ChromeDriver\\chromedriver.exe");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:3000/rooms");
    driver.manage().window().maximize();
//    driver.findElement(By.id("type")).click();
//    {
//      WebElement dropdown = driver.findElement(By.id("type"));
//      dropdown.findElement(By.xpath("//option[. = 'double']")).click();
//    }
//    driver.findElement(By.id("capacity")).click();
//    driver.findElement(By.id("price")).sendKeys("548");
//    driver.findElement(By.id("price")).click();
//    driver.findElement(By.id("pets")).click();
    driver.findElement(By.id("type")).click();
    {
      WebElement dropdown = driver.findElement(By.id("type"));
      dropdown.findElement(By.xpath("//option[. = 'double']")).click();
    }
    driver.findElement(By.id("capacity")).click();
    {
      WebElement dropdown = driver.findElement(By.id("capacity"));
      dropdown.findElement(By.xpath("//option[. = '2']")).click();
    }
    {
      WebElement element = driver.findElement(By.id("price"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("price"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("price"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("price")).sendKeys("567");
    driver.findElement(By.id("price")).click();
    driver.findElement(By.name("maxSize")).click();
    driver.findElement(By.name("maxSize")).click();
    {
      WebElement element = driver.findElement(By.name("maxSize"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("maxSize")).sendKeys("900");
    driver.findElement(By.id("pets")).click();


  }
}
