// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class SizeOfElement{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void CheckSizeofButton() {
    System.setProperty("webdriver.chrome.driver","C:\\ChromeDriver\\chromedriver.exe");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:3000/");
    driver.manage().window().maximize();
    Dimension d=driver.findElement(By.id("OurRoomsBtn")).getSize();
    int height=d.getHeight();
    int width=d.getWidth();
    Assert.assertEquals(40,height);
    Assert.assertEquals(162,width);
  }
}
