// Generated by Selenium IDE
import org.junit.Test;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class StartToEndFlow {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void OverAllFlow() {
    System.setProperty("webdriver.chrome.driver","C:\\ChromeDriver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;

    vars = new HashMap<String, Object>();

    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.cssSelector(".btn-primary:nth-child(4)")).click();
    driver.findElement(By.id("type")).click();
    {
      WebElement dropdown = driver.findElement(By.id("type"));
      dropdown.findElement(By.xpath("//option[. = 'double']")).click();
    }
    {
      WebElement element = driver.findElement(By.id("price"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("price"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("price"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("price")).sendKeys("550");
    driver.findElement(By.id("price")).click();
    driver.findElement(By.name("maxSize")).click();
    driver.findElement(By.name("maxSize")).click();
    {
      WebElement element = driver.findElement(By.name("maxSize"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("maxSize")).sendKeys("800");
    driver.findElement(By.id("pets")).click();
    js.executeScript("window.scrollBy(0,1000)");
    driver.findElement(By.cssSelector(".room:nth-child(2) .btn-primary")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.id("feedbackRoomType")).click();
    driver.findElement(By.id("feedbackRoomType")).sendKeys("double");
    driver.findElement(By.cssSelector(".single-extras:nth-child(1)")).click();
    driver.findElement(By.id("rating")).click();
    driver.findElement(By.id("rating")).sendKeys("4");
    driver.findElement(By.id("recommend")).click();
    driver.findElement(By.id("feedbackTextArea")).click();
    driver.findElement(By.id("feedbackTextArea")).sendKeys("Good");
    driver.findElement(By.id("feedbackSubmit")).click();
  }
}
