// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class SubmitFeedback{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void CheckSizeofButton() {
    System.setProperty("webdriver.chrome.driver","C:\\ChromeDriver\\chromedriver.exe");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:3000/feedback");
    driver.manage().window().maximize();
    driver.findElement(By.id("feedbackRoomType")).click();
    driver.findElement(By.id("feedbackRoomType")).sendKeys("double");
    driver.findElement(By.id("rating")).click();
    driver.findElement(By.id("rating")).sendKeys("4");
    driver.findElement(By.id("recommend")).click();
    driver.findElement(By.id("feedbackTextArea")).click();
    driver.findElement(By.id("feedbackTextArea")).sendKeys("good");
    driver.findElement(By.id("feedbackSubmit")).click();
  }
}
